apiVersion: v1
kind: Service
metadata:
  name: {{ include "demo-app.stableService" . }}
  labels:
    {{- include "demo-app.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  # Argo adds rollouts-pod-template-hash for the stable RS
  selector:
    {{- include "demo-app.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
